{"name": "Проверка логина несуществующим курьером", "status": "passed", "description": "Пытаемся залогиниться несуществующим аккаунтом курьера, получаем ошибку 404 и соответствующее сообщение", "steps": [{"name": "Вход курьера с несуществующими данными", "status": "passed", "start": 1717269285296, "stop": 1717269285463}], "start": 1717269285296, "stop": 1717269285464, "uuid": "416f2172-9716-4cdd-bb25-3da3fdd9575b", "historyId": "b5a007415a4fe82fdd455da5981fbf07", "testCaseId": "b5a007415a4fe82fdd455da5981fbf07", "fullName": "tests.test_login_courier.TestLoginCourier#test_no_such_username_and_password", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "DESKTOP-CENUCRE"}, {"name": "thread", "value": "12636-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}